@postId = 123
@commentId = 123
@profileId = 123

# Posts
GET http://localhost:4000/api/posts

###
POST http://localhost:4000/api/posts

###

GET http://localhost:4000/api/posts/{{postId}}

###

PUT http://localhost:4000/api/posts/{{postId}}

###

POST http://localhost:4000/api/posts/{{postId}}

###

DELETE http://localhost:4000/api/posts/{{postId}}

###

# Comments
POST http://localhost:4000/api/posts/{{postId}}/comments

###

PUT http://localhost:4000/api/posts/{{postId}}/comments/{{commentId}}

###

POST http://localhost:4000/api/posts/{{postId}}/comments/{{commentId}}

###

DELETE http://localhost:4000/api/posts/{{postId}}/comments/{{commentId}}

###

#Users
POST http://localhost:4000/api/login

###

POST http://localhost:4000/api/register

###

PUT http://localhost:4000/api/profile/{{profileId}}