@postId = 123
@commentId = 123
@profileId = 60ab8340f6ef2695f5911ffa
###

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGFiOWFhMzVkYjg1OWVhNDNhYjkyYWYiLCJpYXQiOjE2MjE4NjM4ODMsImV4cCI6MTYyMTkwNzA4M30.ve-pWclPU_HOn7LNeI1mIalSplLGgG1uveE9ZOzocT8

# Posts
GET http://localhost:4000/api/posts

###
POST http://localhost:4000/api/posts

###

GET http://localhost:4000/api/posts/{{postId}}

###

PUT http://localhost:4000/api/posts/{{postId}}

###

POST http://localhost:4000/api/posts/{{postId}}
Authorization: Bearer {{token}}




###

DELETE http://localhost:4000/api/posts/{{postId}}

###

# Comments
POST http://localhost:4000/api/posts/{{postId}}/comments

###

PUT http://localhost:4000/api/posts/{{postId}}/comments/{{commentId}}

###

POST http://localhost:4000/api/posts/{{postId}}/comments/{{commentId}}

###

DELETE http://localhost:4000/api/posts/{{postId}}/comments/{{commentId}}

###

#Users
POST http://localhost:4000/api/login
Content-Type: application/json

{
  "email": "jon@email",
  "password": "pass"
}


###

POST http://localhost:4000/api/register
content-type: application/json

{
  "username": "dan2",
  "password": "pass",
  "passwordConfirmation": "pass",
  "email": "dan2@email"

}

###

PUT http://localhost:4000/api/profile/{{profileId}}
content-type: application/json
Authorization: Bearer {{token}}

{
  "username":"SirDan",
  "email":"dan@email",
  "password":"pass",
  "passwordConfirmation":"pass",
  "image":"https://instagram.flhr3-4.fna.fbcdn.net/v/t51.2885-19/s320x320/90252192_146512903332422_4855195378321981440_n.jpg?tp=1&_nc_ht=instagram.flhr3-4.fna.fbcdn.net&_nc_ohc=ONFuSlbBHP0AX9JXsJV&edm=ABfd0MgBAAAA&ccb=7-4&oh=9ae41dbe4c82ad0af2efd95f83b5099d&oe=60AF40EF&_nc_sid=7bff83",
  "summary":"Dan is Dan",
  "peekcoin":1000
}

###

GET http://localhost:4000/api/profile/{{profileId}}

###

GEt http://localhost:4000/api/profile