@postId = 60abcc1f689a5bb8f0ecd112
@commentId = 60acb7999160e2e5c31a6bf4
@profileId = 60abca973b79a2b874bef109
###

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGFiY2E5NzNiNzlhMmI4NzRiZWYxMDgiLCJpYXQiOjE2MjE5Mjk5MDMsImV4cCI6MTYyMTk3MzEwM30.d-MgrontSdIY8OX2-Xk5M2twU1vHubf0uDM2vsJ6NYU


# Posts
GET http://localhost:4000/api/posts

###
POST http://localhost:4000/api/posts
content-type: application/json
Authorization: Bearer {{token}}

{
  "title":"Posting Comments is fun",
  "text":"...Until it doesn't work...",
  "image":"https://i.kym-cdn.com/photos/images/newsfeed/001/878/329/dfa.jpg"
}
###

GET http://localhost:4000/api/posts/{{postId}}

###

PUT http://localhost:4000/api/posts/{{postId}}
content-type: application/json
Authorization: Bearer {{token}}

{
  "title":"Posting Comments is fun, really really fun... "
}

###

POST http://localhost:4000/api/posts/{{postId}}
Authorization: Bearer {{token}}




###

DELETE http://localhost:4000/api/posts/{{postId}}

###

# Comments
POST http://localhost:4000/api/posts/{{postId}}/comments
content-type: application/json
Authorization: Bearer {{token}}

{
  "text": "this is finally a third comment!"
}

###

PUT http://localhost:4000/api/posts/{{postId}}/comments/{{commentId}}
content-type: application/json
Authorization: Bearer {{token}}

{
  "text":"this is an second edited comment... :)"
}


###
//Liked Comments
POST http://localhost:4000/api/posts/{{postId}}/comments/{{commentId}}
content-type: application/json
Authorization: Bearer {{token}}



###

DELETE http://localhost:4000/api/posts/{{postId}}/comments/{{commentId}}
content-type: application/json
Authorization: Bearer {{token}}

###

#Users
POST http://localhost:4000/api/login
Content-Type: application/json

{
  "email": "craig@email",
  "password": "pass"
}


###

POST http://localhost:4000/api/register
content-type: application/json

{
  "username": "dan2",
  "password": "pass",
  "passwordConfirmation": "pass",
  "email": "dan2@email"

}

###

PUT http://localhost:4000/api/profile/{{profileId}}
content-type: application/json
Authorization: Bearer {{token}}

{
  "username":"SirDan",
  "email":"dan@email",
  "password":"pass",
  "passwordConfirmation":"pass",
  "image":"https://instagram.flhr3-4.fna.fbcdn.net/v/t51.2885-19/s320x320/90252192_146512903332422_4855195378321981440_n.jpg?tp=1&_nc_ht=instagram.flhr3-4.fna.fbcdn.net&_nc_ohc=ONFuSlbBHP0AX9JXsJV&edm=ABfd0MgBAAAA&ccb=7-4&oh=9ae41dbe4c82ad0af2efd95f83b5099d&oe=60AF40EF&_nc_sid=7bff83",
  "summary":"Dan is Not Dan",
  "peekcoin":1000
}

###

GET http://localhost:4000/api/profile/{{profileId}}

###

GEt http://localhost:4000/api/profile